// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvrtkdebyeoiopoajjpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cnRrZGVieWVvaW9wb2FqanB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODI4MzMsImV4cCI6MjA2MjM1ODgzM30.cF_tUwJPbSmf5TnLAPwhViWftyc0j7Os9pgBpPr6ZTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);